export const replies = [
    "That's interesting! Tell me more about it.",
    "I understand what you mean.",
    "Thanks for sharing that with me!",
    "That's a great point!",
    "I'm here to help you with that.",
    "Could you elaborate on that?",
    "I appreciate your perspective.",
    "Let’s explore that idea further.",
    "That makes a lot of sense.",
    "Can you give me an example?",
    "Nice! Keep going.",
    "You're making great progress!",
    "Let me know if you'd like more info.",
    "You're on the right track.",
  ];
  export const accounts = [
    // Accounts (unchanged, already complete)
    {
      id: "1",
      name: "Supardi.Kencur",
      platform: "X",
      image: "https://storage.googleapis.com/a1aa/image/e7d971de-5070-4752-e501-5028b6ef02c3.jpg",
      bgColor: "bg-black",
      badge: 12,
      gradient: false,
      isUnread: true,
      isActive: false,
      timestamp: new Date("2023-10-01T04:02:00"),
      message: "New message from X", 
      time: "04:02 am",    
    },
    {
      id: "2",
      name: "Pesutmahakam12",
      platform: "Instagram",
      image: "https://storage.googleapis.com/a1aa/image/f9afcad2-1806-4f03-c6e9-ac177e496055.jpg",
      bgColor: "bg-gradient-to-tr from-[#f58529] via-[#dd2a7b] to-[#8134af]",
      badge: 24,
      gradient: true,
      badgeColor: "bg-[#a56fff]",
      isUnread: true,
      isActive: false,
      timestamp: new Date("2023-10-01T17:49:00"),
      message: "New Instagram DM", 
      time: "05:49 pm",    
    },
    {
      id: "3",
      name: "+621234567890",
      platform: "Whatsapp",
      image: "https://storage.googleapis.com/a1aa/image/3e45f46d-76fb-4569-481c-ab0a985430ec.jpg",
      bgColor: "bg-[#25d366]",
      badge: 132,
      isUnread: true,
      isActive: false,
      timestamp: new Date("2023-10-01T04:02:00"),
      message: "New WhatsApp message", 
      time: "04:02 am",    
    },
    {
      id: "4",
      name: "Hussein Saddam",
      platform: "Linkedin",
      image: "https://storage.googleapis.com/a1aa/image/a5e60ac4-0764-47a9-aaea-050279acc271.jpg",
      bgColor: "bg-[#0077b5]",
      badge: 2,
      isUnread: true,
      isActive: false,
      timestamp: new Date("2023-10-01T04:02:00"),
      message: "New connection request", 
      time: "04:02 am",    
    },
    {
      id: "5",
      name: "Vladimir.basuki",
      platform: "Tiktok",
      image: "https://storage.googleapis.com/a1aa/image/d15a4269-926a-434d-0339-078ac7f3a4c8.jpg",
      bgColor: "bg-black",
      badge: 16,
      isUnread: true,
      isActive: false,
      timestamp: new Date("2023-10-01T04:02:00"),
      message: "New TikTok notification", 
      time: "04:02 am",    
    },
  
    // Messages (added missing account fields)
    {
      id: "6", 
      name: "Alfredo Workman",
      platform: "Email", 
      image: "https://storage.googleapis.com/a1aa/image/1593f98f-9080-4926-7833-066e649552fb.jpg",
      bgColor: "bg-[#4285F4]", 
      badge: 0,   
      gradient: false, 
      message: "Hi, I noticed a squ...",
      time: "04:02 am",
      isUnread: true,
      isActive: false,
      timestamp: new Date("2023-10-01T04:02:00"),
    },
    {
      id: "7", 
      name: "Kianna George",
      platform: "Messenger", 
      image: "https://storage.googleapis.com/a1aa/image/959e622e-805e-48f3-7a68-dc576c5a3105.jpg",
      bgColor: "bg-[#006AFF]", 
      badge: 0,   
      gradient: false, 
      message: "Hi, I noticed a squ...",
      time: "05:49 pm",
      isUnread: true,
      isActive: false,
      timestamp: new Date("2023-10-01T17:49:00"),
    },
    {
      id: "8", 
      name: "Ann Schleifer",
      platform: "Slack", 
      image: "https://storage.googleapis.com/a1aa/image/aec93123-9edc-46ba-80a2-fdcd8a8321c2.jpg",
      bgColor: "bg-[#4A154B]", 
      badge: 0,   
      gradient: false, 
      message: "Hi, I noticed a squ...",
      time: "01:34 pm",
      isUnread: false,
      isActive: true,
      timestamp: new Date("2023-10-01T13:34:00"),
    },
    {
      id: "9", 
      name: "Craig Culhane",
      platform: "Telegram", 
      image: "https://storage.googleapis.com/a1aa/image/a77eaf3a-ac6f-4a4c-26d7-49e7ad418c72.jpg",
      bgColor: "bg-[#0088CC]", 
      badge: 0,   
      gradient: false, 
      message: "Hi, I noticed a squ...",
      time: "03:49 am",
      isUnread: false,
      isActive: false,
      timestamp: new Date("2023-10-01T03:49:00"),
    }
  ]
  
 